# Generated by Django 5.1.7 on 2025-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
