# Generated by Django 5.1.7 on 2025-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_member_joined_at_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='narxi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
