# Generated by Django 5.1.7 on 2025-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_kirim_narxi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('matn', models.TextField(blank=True, null=True)),
                ('yuborilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
